### ISSUE TITLE
Will you port this to the new api?

### ISSUE THREAD

**Issue by razzeee** [UberMouse/TraktToHummingbird#2]
Would be very nice ;)

**Comment by UberMouse** [comment]
I would like to, I've actually just been updating my hummingbird profile manually since I haven't been watching as much anime so I haven't bothered to fix it since Trakt 2.0 came out. I'll see if I can do it in my R&D time at work in a few days.

**Comment by UberMouse** [comment]
I've had a look and there are a two issues
1. [API url](https://api-v2launch.trakt.tv/users/ubermouse/history/episodes) to get episode history gives me an HTTP 412 with no useful information in the documentation
2. Can't figure out where to get an API key (just oauth stuff which isn't helpful for this), maybe I can just reuse my v1 key I'm not sure

So not sure when I'll have time to look into those.

**Comment by razzeee** [comment]
Head here to create your app and get a key http://trakt.tv/oauth/applications
